-- Script para criação do BD do Esquema Relacional 5
-- Grupo: Filipe Carlos e Matheus Campos

-- criando esquema
CREATE SCHEMA EMPRESA;
USE EMPRESA;

-- criando tabelas
CREATE TABLE PESSOA (
	COD_PESSOA INTEGER NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(20) NOT NULL,
	ENDERECO VARCHAR(255) NOT NULL,
	TIPO CHAR(1) NOT NULL,
	ESPECIALIDADE VARCHAR(20),
	TELEFONE INTEGER(8)
);

CREATE TABLE VEICULO (
	CHASSI VARCHAR(17) NOT NULL,
	MARCA VARCHAR(20) NOT NULL,
	COD_PESSOA INTEGER NOT NULL
);

CREATE TABLE ORDEM_SERVICO (
	NUMERO_OS INTEGER NOT NULL AUTO_INCREMENT,
	DATA_EMISSAO DATE NOT NULL,
	DATA_CONCLUSAO DATE,
	CHASSI VARCHAR(20) NOT NULL,
	ID_EQUIPE INTEGER NOT NULL
);

CREATE TABLE ITEM (
	COD_ITEM INTEGER NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(100),
	NUM_OS INTEGER NOT NULL,
	CHASSI VARCHAR(20) NOT NULL
);

CREATE TABLE PECA (
	COD_PECA INTEGER NOT NULL AUTO_INCREMENT,
	FORNECEDOR VARCHAR(20) NOT NULL
);

CREATE TABLE SERVICO(
	COD_SERVICO INTEGER NOT NULL,
	GARANTIA TINYINT NOT NULL
);

CREATE TABLE DEMANDA (
	COD_ITEM_PECA INTEGER NOT NULL,
	COD_ITEM_SERVICO INTEGER NOT NULL
);

CREATE TABLE EQUIPE(
	ID_EQUIPE INTEGER NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(20) NOT NULL,

	UNIQUE(NOME)
);

CREATE TABLE PERTENCE (
	ID_EQUIPE INTEGER NOT NULL,
	COD_PESSOA INTEGER NOT NULL
);

-- povoando banco de dados
INSERT INTO PESSOA (COD_PESSOA, NOME, ENDERECO, TIPO, ESPECIALIDADE, TELEFONE) VALUES
(NULL, 'Matheus Campos', 'Avenida Tapajós, 125-C', 'M', 'Motor', NULL),
(NULL, 'Filipe Carlos', 'Rua Mamanguape, 100', 'C', NULL, 12345678),
(NULL, 'Edna Wilma', 'Avenida Recife, 3856', 'C', NULL, 87654321),
(NULL, 'Daniel Campos', 'Avenida Barreto de Menezes, 500', 'M', 'Chassi', NULL),
(NULL, 'Carlos Alberto', 'Rua 15, 182', 'M', 'Pneu', NULL),
(NULL, 'Rafael Martins', 'Rua Jangadeiro, 252, Apt: 308', 'C', NULL, 40028922);

INSERT INTO VEICULO (CHASSI, MARCA, COD_PESSOA) VALUES
('9BWHE21JX24060960', 'VOLKSWAGEN', 123456),
('9BKHE220X24060961', 'FIAT', 123456),
('9BCHE23LX24060962', 'NISSAN', 123456),
('9BAHE24MX24060963', 'AUDI', 123456),
('9BDHE25BX24060964', 'BMW', 123456),
('9BFHE26GX24060965', 'CITROEN', 123456);

INSERT INTO ORDEM_SERVICO (NUMERO_OS, DATA_EMISSAO, DATA_CONCLUSAO, CHASSI, ID_EQUIPE) VALUES
(NULL, TO_DATE('16/08/2017', 'DD/MM/AAAA'), TO_DATE('17/08/2017', 'DD/MM/AAAA'), '9BWHE21JX24060960', 000001),
(NULL, TO_DATE('15/08/2017', 'DD/MM/AAAA'), TO_DATE('17/08/2017', 'DD/MM/AAAA'), '9BDHE25BX24060964', 000002),
(NULL, TO_DATE('14/08/2017', 'DD/MM/AAAA'), TO_DATE('14/08/2017', 'DD/MM/AAAA'), '9BFHE26GX24060965', 000003),
(NULL, TO_DATE('14/08/2017', 'DD/MM/AAAA'), NULL, '9BAHE24MX24060963', 000004),
(NULL, TO_DATE('11/08/2017', 'DD/MM/AAAA'), TO_DATE('15/08/2017', 'DD/MM/AAAA'), '9BCHE23LX24060962', 000005),
(NULL, TO_DATE('13/08/2017', 'DD/MM/AAAA'), TO_DATE('14/08/2017', 'DD/MM/AAAA'), '9BKHE220X24060961', 000006);

/*INSERT INTO ITEM (COD_ITEM, DESCRICAO, NUM_OS, CHASSI) VALUES
(NULL, '');

INSERT INTO DEMANDA (COD_ITEM_PECA, COD_ITEM_SERVICO) VALUES
();*/

INSERT INTO EQUIPE (ID_EQUIPE, NOME) VALUES
(NULL, 'EQUIPE 1'),
(NULL, 'EQUIPE 2'),
(NULL, 'EQUIPE 3');

INSERT INTO PERTENCE (ID_EQUIPE, COD_PESSOA) VALUES
(1, 5),
(1, 4),
(1, 1),
(2, 5),
(2, 4),
(3, 1);

-- Aplicando as restrições de integridade
-- Chaves primárias
alter table VEICULO add constraint pk_VEICULO primary key (CHASSI);
alter table ORDEM_SERVICO add constraint pk_ORDEM_SERVICO primary key (NUMERO_OS,CHASSI);
alter table ITEM add constraint pk_ITEM primary key (COD_ITEM);
alter table PECA add constraint pk_PECA primary key (COD_PECA);
alter table SERVICO add constraint pk_SERVICO primary key (COD_SERVICO);
alter table EQUIPE add constraint pk_EQUIPE primary key (ID_EQUIPE);
alter table PERTENCE add constraint pk_PERTENCE primary key (ID_PERTENCE, COD_PERTENCE);
alter table PESSOA add constraint pk_PESSOA primary key (COD_PESSOA);
alter table DEMANDA add constraint pk_DEMANDA primary key (COD_ITEM_PECA,COD_ITEM_SERVICO);

-- Chaves estrangeiras
alter table VEICULO add constraint fk_VEICULO_PESSOA foreign key (COD_PESSOA) references PESSOA(COD_PESSOA);
alter table ORDEM_SERVICO add constraint fk_ORDEM_SERVICO_VEICULO foreign key (CHASSI) references VEICULO(CHASSI);
alter table ORDEM_SERVICO add constraint fk_ORDEM_SERVICO_EQUIPE foreign key (ID_EQUIPE) references EQUIPE(ID_EQUIPE);
alter table ITEM add constraint fk_ITEM_ORDEM_SERVICO foreign key (NUM_OS) references ORDEM_SERVICO(NUMERO_OS);
alter table ITEM add constraint fk_ITEM_VEICULO foreign key (CHASSI) references VEICULO(CHASSI);
alter table PECA add constraint fk_PECA_ITEM foreign key (COD_PECA) references ITEM(COD_ITEM);
alter table SERVICO add constraint fk_SERVICO_ITEM foreign key (COD_SERVICO) references ITEM(COD_ITEM);
alter table DEMANDA add constraint fk_DEMANDA_ITEM foreign key (COD_ITEM_PECA,COD_ITEM_SERVICO) references ITEM(COD_ITEM);
alter table PERTENCE add constraint fk_PERTENCE_EQUIPE foreign key (ID_EQUIPE) references EQUIPE(ID_EQUIPE);
alter table PERTENCE add constraint fk_PERTENCE_PESSOA foreign key (COD_PESSOA) references EQUIPE(COD_PESSOA);
